### ISSUE TITLE
spawn wkhtmltopdf ENOENT

### ISSUE THREAD

**Issue by cascer1** [cheindl/raml2pdf-cli#1]
Hi,

Whenever I run the tool, I get the following exception:

```
>raml2pdf-cli api.raml api.pdf
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn wkhtmltopdf ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'm using raml2pdf-cli version 1.0.3

**Comment by cheindl** [comment]
Is wkhtmltopdf installed on your system? Can you run it directly via command line (i.e. is it within your PATH variable)?

**Comment by Samerkassem** [comment]
It is installed and running by command, AND it's there's a C:\Program Files\wkhtmltopdf\bin in Path env and yet still getting this error
